# Generated by Django 5.1.5 on 2026-04-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0004_alter_message_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
    ]
